name:                factorio-data-extractor
version:             0.1.0.0
github:              "johnsonwj/factorio-data-extractor"
license:             BSD3
author:              "William Johnson"
maintainer:          "example@example.com"
copyright:           "2018 William Johnson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/factorio-data-extractor#readme>

dependencies:
- base >= 4.7 && < 5
- hslua >= 0.9.5
- filepath >= 1.4.2
- bytestring >= 0.10.8


library:
  source-dirs: src

executables:
  factorio-data-extractor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - factorio-data-extractor

tests:
  factorio-data-extractor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - factorio-data-extractor
